Document: xfwm4
Title: Debian xfwm4 Manual
Author: <insert document author here>
Abstract: This manual describes what xfwm4 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/xfwm4/xfwm4.sgml.gz

Format: postscript
Files: /usr/share/doc/xfwm4/xfwm4.ps.gz

Format: text
Files: /usr/share/doc/xfwm4/xfwm4.text.gz

Format: HTML
Index: /usr/share/doc/xfwm4/html/index.html
Files: /usr/share/doc/xfwm4/html/*.html
