/* automatically generated from xfwm4-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (xfwm4_dialog_ui)
#endif
#ifdef __GNUC__
static const char xfwm4_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char xfwm4_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.20\"/><object class=\"GtkAdjustment\" id=\"adjustment1"
  "\"><property name=\"lower\">5</property><property name=\"upper\">2000</"
  "property><property name=\"value\">5</property><property name=\"step_inc"
  "rement\">1</property><property name=\"page_increment\">10</property></o"
  "bject><object class=\"GtkAdjustment\" id=\"adjustment2\"><property name"
  "=\"lower\">5</property><property name=\"upper\">2000</property><propert"
  "y name=\"value\">5</property><property name=\"step_increment\">1</prope"
  "rty><property name=\"page_increment\">10</property></object><object cla"
  "ss=\"GtkAdjustment\" id=\"adjustment3\"><property name=\"lower\">5</pro"
  "perty><property name=\"upper\">100</property><property name=\"value\">2"
  "0</property><property name=\"step_increment\">1</property><property nam"
  "e=\"page_increment\">10</property></object><object class=\"GtkAdjustmen"
  "t\" id=\"adjustment4\"><property name=\"lower\">5</property><property n"
  "ame=\"upper\">100</property><property name=\"value\">20</property><prop"
  "erty name=\"step_increment\">1</property><property name=\"page_incremen"
  "t\">10</property></object><object class=\"GtkImage\" id=\"image7\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"icon_name\">window-close</property></objec"
  "t><object class=\"GtkImage\" id=\"image8\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"icon_name\">help-browser</property></object><object class=\"XfceTi"
  "tledDialog\" id=\"main-dialog\"><property name=\"can_focus\">False</pro"
  "perty><property name=\"title\" translatable=\"yes\">Window Manager</pro"
  "perty><property name=\"window_position\">center-on-parent</property><pr"
  "operty name=\"icon_name\">xfwm4</property><property name=\"type_hint\">"
  "dialog</property><property name=\"subtitle\" translatable=\"yes\">Confi"
  "gure window behavior and shortcuts</property><child internal-child=\"vb"
  "ox\"><object class=\"GtkBox\" id=\"main-vbox\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">False</property><propert"
  "y name=\"orientation\">vertical</property><child internal-child=\"actio"
  "n_area\"><object class=\"GtkButtonBox\" id=\"dialog-action_area1\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"layout_style\">end</property><child><objec"
  "t class=\"GtkButton\" id=\"help_button\"><property name=\"label\" trans"
  "latable=\"yes\">_Help</property><property name=\"use_action_appearance\""
  ">False</property><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">True</property><property name=\"receives_default\">Tru"
  "e</property><property name=\"image\">image8</property><property name=\""
  "use_underline\">True</property></object><packing><property name=\"expan"
  "d\">False</property><property name=\"fill\">False</property><property n"
  "ame=\"position\">0</property><property name=\"secondary\">True</propert"
  "y></packing></child><child><object class=\"GtkButton\" id=\"close_butto"
  "n\"><property name=\"label\" translatable=\"yes\">_Close</property><pro"
  "perty name=\"use_action_appearance\">False</property><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">True</property><pr"
  "operty name=\"receives_default\">True</property><property name=\"image\""
  ">image7</property><property name=\"use_underline\">True</property></obj"
  "ect><packing><property name=\"expand\">False</property><property name=\""
  "fill\">False</property><property name=\"position\">1</property></packin"
  "g></child></object><packing><property name=\"expand\">False</property><"
  "property name=\"fill\">True</property><property name=\"pack_type\">end<"
  "/property><property name=\"position\">0</property></packing></child><ch"
  "ild><object class=\"GtkNotebook\" id=\"plug-child\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">True</property><pro"
  "perty name=\"border_width\">6</property><child><object class=\"GtkBox\""
  " id=\"hbox7\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"orientation\">horizontal"
  "</property><property name=\"border_width\">12</property><property name="
  "\"spacing\">12</property><child><object class=\"GtkFrame\" id=\"frame13"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"label_xalign\">0</property><propert"
  "y name=\"shadow_type\">none</property><child><object class=\"GtkAlignme"
  "nt\" id=\"alignment11\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"top_padding\">"
  "6</property><property name=\"left_padding\">12</property><child><object"
  " class=\"GtkScrolledWindow\" id=\"scrolledwindow3\"><property name=\"wi"
  "dth_request\">200</property><property name=\"visible\">True</property><"
  "property name=\"can_focus\">True</property><property name=\"hscrollbar_"
  "policy\">automatic</property><property name=\"vscrollbar_policy\">autom"
  "atic</property><property name=\"shadow_type\">in</property><child><obje"
  "ct class=\"GtkTreeView\" id=\"theme_name_treeview\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">True</property><pro"
  "perty name=\"headers_visible\">False</property></object></child></objec"
  "t></child></object></child><child type=\"label\"><object class=\"GtkLab"
  "el\" id=\"label32\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property><property name=\"label\" translatab"
  "le=\"yes\">&lt;b&gt;The_me&lt;/b&gt;</property><property name=\"use_mar"
  "kup\">True</property><property name=\"use_underline\">True</property></"
  "object></child></object><packing><property name=\"expand\">True</proper"
  "ty><property name=\"fill\">True</property><property name=\"position\">0"
  "</property></packing></child><child><object class=\"GtkBox\" id=\"vbox1"
  "2\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"orientation\">vertical</property><"
  "property name=\"spacing\">6</property><child><object class=\"GtkFrame\""
  " id=\"frame10\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"label_xalign\">0</prop"
  "erty><property name=\"shadow_type\">none</property><child><object class"
  "=\"GtkAlignment\" id=\"alignment14\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"b"
  "order_width\">6</property><property name=\"bottom_padding\">6</property"
  "><property name=\"left_padding\">12</property><child><object class=\"Gt"
  "kFontButton\" id=\"title_font_button\"><property name=\"use_action_appe"
  "arance\">False</property><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">True</property><property name=\"receives_defau"
  "lt\">True</property></object></child></object></child><child type=\"lab"
  "el\"><object class=\"GtkLabel\" id=\"label23\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">False</property><propert"
  "y name=\"label\" translatable=\"yes\">&lt;b&gt;Title fon_t&lt;/b&gt;</p"
  "roperty><property name=\"use_markup\">True</property><property name=\"u"
  "se_underline\">True</property><property name=\"mnemonic_widget\">title_"
  "font_button</property></object></child></object><packing><property name"
  "=\"expand\">False</property><property name=\"fill\">False</property><pr"
  "operty name=\"position\">0</property></packing></child><child><object c"
  "lass=\"GtkFrame\" id=\"frame11\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"label"
  "_xalign\">0</property><property name=\"shadow_type\">none</property><ch"
  "ild><object class=\"GtkAlignment\" id=\"title_align_box\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"border_width\">6</property><property name=\"bottom_"
  "padding\">6</property><property name=\"left_padding\">12</property><chi"
  "ld><object class=\"GtkComboBox\" id=\"title_align_combo\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty></object></child></object></child><child type=\"label\"><object clas"
  "s=\"GtkLabel\" id=\"label24\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">False</property><property name=\"label\" "
  "translatable=\"yes\">&lt;b&gt;Title _alignment&lt;/b&gt;</property><pro"
  "perty name=\"use_markup\">True</property><property name=\"use_underline"
  "\">True</property><property name=\"mnemonic_widget\">title_align_combo<"
  "/property></object></child></object><packing><property name=\"expand\">"
  "False</property><property name=\"fill\">False</property><property name="
  "\"position\">1</property></packing></child><child><object class=\"GtkFr"
  "ame\" id=\"frame12\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"label_xalign\">0<"
  "/property><property name=\"shadow_type\">none</property><child><object "
  "class=\"GtkAlignment\" id=\"button_layout_box\"><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">False</property><proper"
  "ty name=\"bottom_padding\">6</property><property name=\"left_padding\">"
  "12</property><child><object class=\"GtkBox\" id=\"vbox13\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"orientation\">vertical</property><property name=\""
  "border_width\">6</property><property name=\"spacing\">6</property><chil"
  "d><object class=\"GtkLabel\" id=\"label26\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"xalign\">0</property><property name=\"label\" translatable=\"yes\""
  ">Click and drag the buttons to change the layout</property></object><pa"
  "cking><property name=\"expand\">True</property><property name=\"fill\">"
  "True</property><property name=\"position\">0</property></packing></chil"
  "d><child><object class=\"GtkFrame\" id=\"active-frame\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">False</property"
  "><property name=\"label_xalign\">0</property><child><object class=\"Gtk"
  "Alignment\" id=\"alignment17\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"border_"
  "width\">6</property><child><object class=\"GtkBox\" id=\"active-box\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"orientation\">horizontal</property><pro"
  "perty name=\"spacing\">6</property><child><object class=\"GtkButton\" i"
  "d=\"button-layout-|\"><property name=\"label\" translatable=\"yes\">Tit"
  "le</property><property name=\"use_action_appearance\">False</property><"
  "property name=\"visible\">True</property><property name=\"can_focus\">T"
  "rue</property><property name=\"receives_default\">True</property><prope"
  "rty name=\"tooltip_text\" translatable=\"yes\">The window title cannot "
  "be removed</property></object><packing><property name=\"expand\">False<"
  "/property><property name=\"fill\">False</property><property name=\"posi"
  "tion\">0</property></packing></child></object></child></object></child>"
  "<child type=\"label\"><object class=\"GtkLabel\" id=\"label27\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property><property name=\"label\" translatable=\"yes\">Active</property"
  "><property name=\"use_markup\">True</property></object></child></object"
  "><packing><property name=\"expand\">True</property><property name=\"fil"
  "l\">True</property><property name=\"position\">1</property></packing></"
  "child><child><object class=\"GtkFrame\" id=\"hidden-frame\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"label_xalign\">0</property><child><object class=\""
  "GtkAlignment\" id=\"alignment18\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"bord"
  "er_width\">6</property><child><object class=\"GtkBox\" id=\"hidden-box\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"orientation\">horizontal</property><p"
  "roperty name=\"spacing\">6</property><child><object class=\"GtkButton\""
  " id=\"button-layout-O\"><property name=\"use_action_appearance\">False<"
  "/property><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">True</property><property name=\"receives_default\">True</prop"
  "erty><property name=\"tooltip_text\" translatable=\"yes\">Menu</propert"
  "y><child><object class=\"GtkImage\" id=\"image1\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"icon_name\">xfce-wm-menu</property></object></child></objec"
  "t><packing><property name=\"expand\">False</property><property name=\"f"
  "ill\">False</property><property name=\"position\">0</property></packing"
  "></child><child><object class=\"GtkButton\" id=\"button-layout-T\"><pro"
  "perty name=\"use_action_appearance\">False</property><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">True</property><pr"
  "operty name=\"receives_default\">True</property><property name=\"toolti"
  "p_text\" translatable=\"yes\">Stick</property><child><object class=\"Gt"
  "kImage\" id=\"image2\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"icon_name\">xfc"
  "e-wm-stick</property></object></child></object><packing><property name="
  "\"expand\">False</property><property name=\"fill\">False</property><pro"
  "perty name=\"position\">1</property></packing></child><child><object cl"
  "ass=\"GtkButton\" id=\"button-layout-S\"><property name=\"use_action_ap"
  "pearance\">False</property><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">True</property><property name=\"receives_def"
  "ault\">True</property><property name=\"tooltip_text\" translatable=\"ye"
  "s\">Shade</property><child><object class=\"GtkImage\" id=\"image3\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Fal"
  "se</property><property name=\"icon_name\">xfce-wm-shade</property></obj"
  "ect></child></object><packing><property name=\"expand\">False</property"
  "><property name=\"fill\">False</property><property name=\"position\">2<"
  "/property></packing></child><child><object class=\"GtkButton\" id=\"but"
  "ton-layout-H\"><property name=\"use_action_appearance\">False</property"
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><property name=\"receives_default\">True</property><pro"
  "perty name=\"tooltip_text\" translatable=\"yes\">Minimize</property><ch"
  "ild><object class=\"GtkImage\" id=\"image4\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"icon_name\">xfce-wm-minimize</property></object></child></object"
  "><packing><property name=\"expand\">False</property><property name=\"fi"
  "ll\">False</property><property name=\"position\">3</property></packing>"
  "</child><child><object class=\"GtkButton\" id=\"button-layout-M\"><prop"
  "erty name=\"use_action_appearance\">False</property><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">True</property><pro"
  "perty name=\"receives_default\">True</property><property name=\"tooltip"
  "_text\" translatable=\"yes\">Maximize</property><child><object class=\""
  "GtkImage\" id=\"image5\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"icon_name\">x"
  "fce-wm-maximize</property></object></child></object><packing><property "
  "name=\"expand\">False</property><property name=\"fill\">False</property"
  "><property name=\"position\">4</property></packing></child><child><obje"
  "ct class=\"GtkButton\" id=\"button-layout-C\"><property name=\"use_acti"
  "on_appearance\">False</property><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">True</property><property name=\"receive"
  "s_default\">True</property><property name=\"tooltip_text\" translatable"
  "=\"yes\">Close</property><child><object class=\"GtkImage\" id=\"image6\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"icon_name\">xfce-wm-close</property><"
  "/object></child></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">False</property><property name=\"position\""
  ">5</property></packing></child></object></child></object></child><child"
  " type=\"label\"><object class=\"GtkLabel\" id=\"label28\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"label\" translatable=\"yes\">Hidden</property><prop"
  "erty name=\"use_markup\">True</property></object></child></object><pack"
  "ing><property name=\"expand\">True</property><property name=\"fill\">Tr"
  "ue</property><property name=\"position\">2</property></packing></child>"
  "</object></child></object></child><child type=\"label\"><object class=\""
  "GtkLabel\" id=\"label25\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"label\" tran"
  "slatable=\"yes\">&lt;b&gt;Button layout&lt;/b&gt;</property><property n"
  "ame=\"use_markup\">True</property></object></child></object><packing><p"
  "roperty name=\"expand\">False</property><property name=\"fill\">False</"
  "property><property name=\"position\">2</property></packing></child></ob"
  "ject><packing><property name=\"expand\">True</property><property name=\""
  "fill\">True</property><property name=\"position\">1</property></packing"
  "></child></object></child><child type=\"tab\"><object class=\"GtkLabel\""
  " id=\"label1\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"label\" translatable=\""
  "yes\">_Style</property><property name=\"use_underline\">True</property>"
  "</object><packing><property name=\"tab_fill\">False</property></packing"
  "></child><child><object class=\"GtkBox\" id=\"vbox10\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"orientation\">vertical</property><property name=\"borde"
  "r_width\">12</property><property name=\"spacing\">6</property><child><o"
  "bject class=\"GtkLabel\" id=\"label22\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"xalign\">0</property><property name=\"label\" translatable=\"yes\">De"
  "fine shortcuts to perform _window manager actions:</property><property "
  "name=\"use_markup\">True</property><property name=\"use_underline\">Tru"
  "e</property></object><packing><property name=\"expand\">False</property"
  "><property name=\"fill\">False</property><property name=\"position\">0<"
  "/property></packing></child><child><object class=\"GtkBox\" id=\"vbox11"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"orientation\">vertical</property><p"
  "roperty name=\"spacing\">6</property><child><object class=\"GtkScrolled"
  "Window\" id=\"scrolledwindow2\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">True</property><property name=\"hscroll"
  "bar_policy\">never</property><property name=\"vscrollbar_policy\">autom"
  "atic</property><property name=\"shadow_type\">in</property><child><obje"
  "ct class=\"GtkTreeView\" id=\"shortcuts_treeview\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">True</property></obj"
  "ect></child></object><packing><property name=\"expand\">True</property>"
  "<property name=\"fill\">True</property><property name=\"position\">0</p"
  "roperty></packing></child><child><placeholder/></child></object><packin"
  "g><property name=\"expand\">True</property><property name=\"fill\">True"
  "</property><property name=\"position\">1</property></packing></child><c"
  "hild><object class=\"GtkAlignment\" id=\"alignment15\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"yalign\">0</property><property name=\"xscale\">0</prope"
  "rty><child><object class=\"GtkBox\" id=\"hbox5\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"orientation\">horizontal</property><property name=\"spacing\""
  ">6</property><child><object class=\"GtkButton\" id=\"shortcuts_edit_but"
  "ton\"><property name=\"label\">gtk-edit</property><property name=\"use_"
  "action_appearance\">False</property><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">True</property><property name=\"rec"
  "eives_default\">True</property><property name=\"use_stock\">True</prope"
  "rty></object><packing><property name=\"expand\">False</property><proper"
  "ty name=\"fill\">False</property><property name=\"position\">0</propert"
  "y></packing></child><child><object class=\"GtkButton\" id=\"shortcuts_c"
  "lear_button\"><property name=\"label\">gtk-clear</property><property na"
  "me=\"use_action_appearance\">False</property><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"receives_default\">True</property><property name=\"use_stock\">Tr"
  "ue</property></object><packing><property name=\"expand\">False</propert"
  "y><property name=\"fill\">False</property><property name=\"position\">1"
  "</property></packing></child><child><object class=\"GtkButton\" id=\"sh"
  "ortcuts_reset_button\"><property name=\"label\" translatable=\"yes\">_R"
  "eset to Defaults</property><property name=\"use_action_appearance\">Fal"
  "se</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">True</pr"
  "operty><property name=\"use_underline\">True</property></object><packin"
  "g><property name=\"expand\">False</property><property name=\"fill\">Fal"
  "se</property><property name=\"padding\">15</property><property name=\"p"
  "ack_type\">end</property><property name=\"position\">2</property></pack"
  "ing></child></object></child></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">False</property><property name"
  "=\"position\">2</property></packing></child></object><packing><property"
  " name=\"position\">1</property></packing></child><child type=\"tab\"><o"
  "bject class=\"GtkLabel\" id=\"label2\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "label\" translatable=\"yes\">_Keyboard</property><property name=\"use_u"
  "nderline\">True</property></object><packing><property name=\"position\""
  ">1</property><property name=\"tab_fill\">False</property></packing></ch"
  "ild><child><object class=\"GtkBox\" id=\"vbox7\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"orientation\">vertical</property><property name=\"border_wid"
  "th\">12</property><property name=\"spacing\">6</property><child><object"
  " class=\"GtkFrame\" id=\"frame5\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"labe"
  "l_xalign\">0</property><property name=\"shadow_type\">none</property><c"
  "hild><object class=\"GtkAlignment\" id=\"alignment7\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"border_width\">6</property><property name=\"bottom_padd"
  "ing\">6</property><property name=\"left_padding\">12</property><child><"
  "object class=\"GtkBox\" id=\"vbox14\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "orientation\">vertical</property><property name=\"spacing\">6</property"
  "><child><object class=\"GtkBox\" id=\"hbox3\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"orientation\">horizontal</property><property name=\"spacing\">12"
  "</property><property name=\"homogeneous\">True</property><child><object"
  " class=\"GtkRadioButton\" id=\"click_to_focus_radio\"><property name=\""
  "label\" translatable=\"yes\">Click to foc_us</property><property name=\""
  "use_action_appearance\">False</property><property name=\"visible\">True"
  "</property><property name=\"can_focus\">True</property><property name=\""
  "receives_default\">False</property><property name=\"use_underline\">Tru"
  "e</property><property name=\"draw_indicator\">True</property></object><"
  "packing><property name=\"expand\">True</property><property name=\"fill\""
  ">True</property><property name=\"position\">0</property></packing></chi"
  "ld><child><object class=\"GtkRadioButton\" id=\"focus_follows_mouse_rad"
  "io\"><property name=\"label\" translatable=\"yes\">Focus follows _mouse"
  "</property><property name=\"use_action_appearance\">False</property><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Tru"
  "e</property><property name=\"receives_default\">False</property><proper"
  "ty name=\"use_underline\">True</property><property name=\"draw_indicato"
  "r\">True</property><property name=\"group\">click_to_focus_radio</prope"
  "rty></object><packing><property name=\"expand\">True</property><propert"
  "y name=\"fill\">True</property><property name=\"position\">1</property>"
  "</packing></child></object><packing><property name=\"expand\">True</pro"
  "perty><property name=\"fill\">True</property><property name=\"position\""
  ">0</property></packing></child><child><object class=\"GtkLabel\" id=\"l"
  "abel29\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"xalign\">0</property><propert"
  "y name=\"label\" translatable=\"yes\">_Delay before window receives foc"
  "us:</property><property name=\"use_markup\">True</property><property na"
  "me=\"use_underline\">True</property><property name=\"mnemonic_widget\">"
  "focus_delay_scale</property></object><packing><property name=\"expand\""
  ">True</property><property name=\"fill\">True</property><property name=\""
  "position\">1</property></packing></child><child><object class=\"GtkAlig"
  "nment\" id=\"alignment19\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"left_paddin"
  "g\">12</property><child><object class=\"GtkBox\" id=\"focus_delay_hbox\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"orientation\">horizontal</property><p"
  "roperty name=\"spacing\">12</property><child><object class=\"GtkLabel\""
  " id=\"label30\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"label\" translatable=\""
  "yes\" comments=\"Focus delay\">&lt;i&gt;Short&lt;/i&gt;</property><prop"
  "erty name=\"use_markup\">True</property></object><packing><property nam"
  "e=\"expand\">False</property><property name=\"fill\">False</property><p"
  "roperty name=\"position\">0</property></packing></child><child><object "
  "class=\"GtkScale\" id=\"focus_delay_scale\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">True</property><property na"
  "me=\"orientation\">horizontal</property><property name=\"adjustment\">a"
  "djustment1</property><property name=\"draw_value\">False</property></ob"
  "ject><packing><property name=\"expand\">True</property><property name=\""
  "fill\">True</property><property name=\"position\">1</property></packing"
  "></child><child><object class=\"GtkLabel\" id=\"label31\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"label\" translatable=\"yes\" comments=\"Focus delay"
  "\">&lt;i&gt;Long&lt;/i&gt;</property><property name=\"use_markup\">True"
  "</property></object><packing><property name=\"expand\">False</property>"
  "<property name=\"fill\">False</property><property name=\"position\">2</"
  "property></packing></child></object></child></object><packing><property"
  " name=\"expand\">True</property><property name=\"fill\">True</property>"
  "<property name=\"position\">2</property></packing></child></object></ch"
  "ild></object></child><child type=\"label\"><object class=\"GtkLabel\" i"
  "d=\"label15\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"label\" translatable=\"y"
  "es\">&lt;b&gt;Focus model&lt;/b&gt;</property><property name=\"use_mark"
  "up\">True</property></object></child></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">False</property><prope"
  "rty name=\"position\">0</property></packing></child><child><object clas"
  "s=\"GtkFrame\" id=\"frame6\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"label_xal"
  "ign\">0</property><property name=\"shadow_type\">none</property><child>"
  "<object class=\"GtkAlignment\" id=\"alignment8\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"border_width\">6</property><property name=\"bottom_padding\""
  ">6</property><property name=\"left_padding\">12</property><child><objec"
  "t class=\"GtkCheckButton\" id=\"focus_new_check\"><property name=\"labe"
  "l\" translatable=\"yes\">Automatically give focus to _newly created win"
  "dows</property><property name=\"use_action_appearance\">False</property"
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><property name=\"receives_default\">False</property><pr"
  "operty name=\"use_underline\">True</property><property name=\"draw_indi"
  "cator\">True</property></object></child></object></child><child type=\""
  "label\"><object class=\"GtkLabel\" id=\"label16\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"label\" translatable=\"yes\">&lt;b&gt;New window focus&lt;/"
  "b&gt;</property><property name=\"use_markup\">True</property></object><"
  "/child></object><packing><property name=\"expand\">False</property><pro"
  "perty name=\"fill\">False</property><property name=\"position\">1</prop"
  "erty></packing></child><child><object class=\"GtkFrame\" id=\"frame7\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "False</property><property name=\"label_xalign\">0</property><property n"
  "ame=\"shadow_type\">none</property><child><object class=\"GtkAlignment\""
  " id=\"alignment9\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"border_width\">6</p"
  "roperty><property name=\"bottom_padding\">6</property><property name=\""
  "left_padding\">12</property><child><object class=\"GtkBox\" id=\"vbox8\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"orientation\">vertical</property><pro"
  "perty name=\"spacing\">6</property><child><object class=\"GtkCheckButto"
  "n\" id=\"raise_on_focus_check\"><property name=\"label\" translatable=\""
  "yes\">Automatically _raise windows when they receive focus</property><p"
  "roperty name=\"use_action_appearance\">False</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"receives_default\">False</property><property name=\"use_"
  "underline\">True</property><property name=\"draw_indicator\">True</prop"
  "erty></object><packing><property name=\"expand\">True</property><proper"
  "ty name=\"fill\">True</property><property name=\"position\">0</property"
  "></packing></child><child><object class=\"GtkBox\" id=\"vbox9\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property><property name=\"orientation\">vertical</property><property na"
  "me=\"spacing\">6</property><child><object class=\"GtkLabel\" id=\"label"
  "19\"><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">False</property><property name=\"xalign\">0</property><property na"
  "me=\"label\" translatable=\"yes\">Delay _before raising focused window:"
  "</property><property name=\"use_underline\">True</property><property na"
  "me=\"mnemonic_widget\">focus_raise_delay_scale</property></object><pack"
  "ing><property name=\"expand\">False</property><property name=\"fill\">F"
  "alse</property><property name=\"position\">0</property></packing></chil"
  "d><child><object class=\"GtkAlignment\" id=\"alignment1\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"left_padding\">12</property><child><object class=\""
  "GtkBox\" id=\"hbox4\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property><property name=\"orientation\">ho"
  "rizontal</property><property name=\"spacing\">12</property><child><obje"
  "ct class=\"GtkLabel\" id=\"label20\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"l"
  "abel\" translatable=\"yes\" comments=\"Raise focus delay\">&lt;i&gt;Sho"
  "rt&lt;/i&gt;</property><property name=\"use_markup\">True</property></o"
  "bject><packing><property name=\"expand\">False</property><property name"
  "=\"fill\">False</property><property name=\"position\">0</property></pac"
  "king></child><child><object class=\"GtkScale\" id=\"focus_raise_delay_s"
  "cale\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">True</property><property name=\"orientation\">horizontal</proper"
  "ty><property name=\"adjustment\">adjustment2</property><property name=\""
  "draw_value\">False</property></object><packing><property name=\"expand\""
  ">True</property><property name=\"fill\">True</property><property name=\""
  "position\">1</property></packing></child><child><object class=\"GtkLabe"
  "l\" id=\"label21\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"label\" translatabl"
  "e=\"yes\" comments=\"Raise focus delay\">&lt;i&gt;Long&lt;/i&gt;</prope"
  "rty><property name=\"use_markup\">True</property></object><packing><pro"
  "perty name=\"expand\">False</property><property name=\"fill\">False</pr"
  "operty><property name=\"position\">2</property></packing></child></obje"
  "ct></child></object><packing><property name=\"expand\">True</property><"
  "property name=\"fill\">True</property><property name=\"position\">1</pr"
  "operty></packing></child></object><packing><property name=\"expand\">Tr"
  "ue</property><property name=\"fill\">True</property><property name=\"po"
  "sition\">1</property></packing></child></object></child></object></chil"
  "d><child type=\"label\"><object class=\"GtkLabel\" id=\"label17\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"label\" translatable=\"yes\">&lt;b&gt;Raise"
  " on focus&lt;/b&gt;</property><property name=\"use_markup\">True</prope"
  "rty></object></child></object><packing><property name=\"expand\">False<"
  "/property><property name=\"fill\">False</property><property name=\"posi"
  "tion\">2</property></packing></child><child><object class=\"GtkFrame\" "
  "id=\"frame8\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"label_xalign\">0</proper"
  "ty><property name=\"shadow_type\">none</property><child><object class=\""
  "GtkAlignment\" id=\"alignment10\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"bord"
  "er_width\">6</property><property name=\"bottom_padding\">6</property><p"
  "roperty name=\"left_padding\">12</property><child><object class=\"GtkCh"
  "eckButton\" id=\"raise_on_click_check\"><property name=\"label\" transl"
  "atable=\"yes\">Raise window when clicking _inside application window</p"
  "roperty><property name=\"use_action_appearance\">False</property><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">True</"
  "property><property name=\"receives_default\">False</property><property "
  "name=\"use_underline\">True</property><property name=\"draw_indicator\""
  ">True</property></object></child></object></child><child type=\"label\""
  "><object class=\"GtkLabel\" id=\"label18\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"label\" translatable=\"yes\">&lt;b&gt;Raise on click&lt;/b&gt;</pr"
  "operty><property name=\"use_markup\">True</property></object></child></"
  "object><packing><property name=\"expand\">False</property><property nam"
  "e=\"fill\">False</property><property name=\"position\">3</property></pa"
  "cking></child></object><packing><property name=\"position\">2</property"
  "></packing></child><child type=\"tab\"><object class=\"GtkLabel\" id=\""
  "label3\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"label\" translatable=\"yes\">"
  "_Focus</property><property name=\"use_underline\">True</property></obje"
  "ct><packing><property name=\"position\">2</property><property name=\"ta"
  "b_fill\">False</property></packing></child><child><object class=\"GtkBo"
  "x\" id=\"vbox1\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property><property name=\"orientation\">vertica"
  "l</property><property name=\"border_width\">12</property><property name"
  "=\"spacing\">6</property><child><object class=\"GtkFrame\" id=\"frame1\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"label_xalign\">0</property><property "
  "name=\"shadow_type\">none</property><child><object class=\"GtkAlignment"
  "\" id=\"alignment2\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"border_width\">6<"
  "/property><property name=\"bottom_padding\">6</property><property name="
  "\"left_padding\">12</property><child><object class=\"GtkBox\" id=\"vbox"
  "2\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"orientation\">vertical</property><"
  "property name=\"spacing\">6</property><child><object class=\"GtkBox\" i"
  "d=\"hbox8\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"orientation\">horizontal</"
  "property><child><object class=\"GtkCheckButton\" id=\"snap_to_border_ch"
  "eck\"><property name=\"label\" translatable=\"yes\">To screen _borders<"
  "/property><property name=\"use_action_appearance\">False</property><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">True"
  "</property><property name=\"receives_default\">False</property><propert"
  "y name=\"use_underline\">True</property><property name=\"draw_indicator"
  "\">True</property></object><packing><property name=\"expand\">True</pro"
  "perty><property name=\"fill\">True</property><property name=\"position\""
  ">0</property></packing></child><child><object class=\"GtkCheckButton\" "
  "id=\"snap_to_window_check\"><property name=\"label\" translatable=\"yes"
  "\">To other _windows</property><property name=\"use_action_appearance\""
  ">False</property><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">True</property><property name=\"receives_default\">Fal"
  "se</property><property name=\"use_underline\">True</property><property "
  "name=\"draw_indicator\">True</property></object><packing><property name"
  "=\"expand\">True</property><property name=\"fill\">True</property><prop"
  "erty name=\"position\">1</property></packing></child></object><packing>"
  "<property name=\"expand\">True</property><property name=\"fill\">True</"
  "property><property name=\"position\">0</property></packing></child><chi"
  "ld><object class=\"GtkBox\" id=\"vbox5\"><property name=\"visible\">Tru"
  "e</property><property name=\"can_focus\">False</property><property name"
  "=\"orientation\">vertical</property><property name=\"spacing\">6</prope"
  "rty><child><object class=\"GtkLabel\" id=\"label9\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"xalign\">0</property><property name=\"label\" translatabl"
  "e=\"yes\">Dis_tance:</property><property name=\"use_underline\">True</p"
  "roperty><property name=\"mnemonic_widget\">snap_width_scale</property><"
  "/object><packing><property name=\"expand\">True</property><property nam"
  "e=\"fill\">True</property><property name=\"position\">0</property></pac"
  "king></child><child><object class=\"GtkAlignment\" id=\"alignment6\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"left_padding\">12</property><child><obje"
  "ct class=\"GtkBox\" id=\"hbox1\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"orien"
  "tation\">horizontal</property><property name=\"spacing\">12</property><"
  "child><object class=\"GtkLabel\" id=\"label11\"><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">False</property><proper"
  "ty name=\"label\" translatable=\"yes\" comments=\"Snapping distance\">&"
  "lt;i&gt;Small&lt;/i&gt;</property><property name=\"use_markup\">True</p"
  "roperty></object><packing><property name=\"expand\">False</property><pr"
  "operty name=\"fill\">False</property><property name=\"position\">0</pro"
  "perty></packing></child><child><object class=\"GtkScale\" id=\"snap_wid"
  "th_scale\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">True</property><property name=\"orientation\">horizontal</pr"
  "operty><property name=\"adjustment\">adjustment3</property><property na"
  "me=\"restrict_to_fill_level\">False</property><property name=\"draw_val"
  "ue\">False</property></object><packing><property name=\"expand\">True</"
  "property><property name=\"fill\">True</property><property name=\"positi"
  "on\">1</property></packing></child><child><object class=\"GtkLabel\" id"
  "=\"label12\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"label\" translatable=\"yes"
  "\" comments=\"Snapping distance\">&lt;i&gt;Wide&lt;/i&gt;</property><pr"
  "operty name=\"use_markup\">True</property></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">False</property>"
  "<property name=\"position\">2</property></packing></child></object></ch"
  "ild></object><packing><property name=\"expand\">True</property><propert"
  "y name=\"fill\">True</property><property name=\"position\">1</property>"
  "</packing></child></object><packing><property name=\"expand\">True</pro"
  "perty><property name=\"fill\">True</property><property name=\"position\""
  ">1</property></packing></child></object></child></object></child><child"
  " type=\"label\"><object class=\"GtkLabel\" id=\"label5\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">False</propert"
  "y><property name=\"label\" translatable=\"yes\">&lt;b&gt;Windows snappi"
  "ng&lt;/b&gt;</property><property name=\"use_markup\">True</property></o"
  "bject></child></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"fill\">True</property><property name=\"position\">0"
  "</property></packing></child><child><object class=\"GtkFrame\" id=\"fra"
  "me2\"><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">False</property><property name=\"label_xalign\">0</property><prop"
  "erty name=\"shadow_type\">none</property><child><object class=\"GtkAlig"
  "nment\" id=\"alignment3\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"border_width"
  "\">6</property><property name=\"bottom_padding\">6</property><property "
  "name=\"left_padding\">12</property><child><object class=\"GtkBox\" id=\""
  "vbox4\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"orientation\">vertical</proper"
  "ty><property name=\"spacing\">6</property><child><object class=\"GtkBox"
  "\" id=\"hbox9\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"orientation\">horizont"
  "al</property><child><object class=\"GtkCheckButton\" id=\"wrap_workspac"
  "es_check\"><property name=\"label\" translatable=\"yes\">With the mouse"
  " _pointer</property><property name=\"use_action_appearance\">False</pro"
  "perty><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">True</property><property name=\"receives_default\">False</propert"
  "y><property name=\"use_underline\">True</property><property name=\"draw"
  "_indicator\">True</property></object><packing><property name=\"expand\""
  ">True</property><property name=\"fill\">True</property><property name=\""
  "position\">0</property></packing></child><child><object class=\"GtkChec"
  "kButton\" id=\"wrap_windows_check\"><property name=\"label\" translatab"
  "le=\"yes\">With a _dragged window</property><property name=\"use_action"
  "_appearance\">False</property><property name=\"visible\">True</property"
  "><property name=\"can_focus\">True</property><property name=\"receives_"
  "default\">False</property><property name=\"use_underline\">True</proper"
  "ty><property name=\"draw_indicator\">True</property></object><packing><"
  "property name=\"expand\">True</property><property name=\"fill\">True</p"
  "roperty><property name=\"position\">1</property></packing></child></obj"
  "ect><packing><property name=\"expand\">True</property><property name=\""
  "fill\">True</property><property name=\"position\">0</property></packing"
  "></child><child><object class=\"GtkBox\" id=\"vbox6\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"orientation\">vertical</property><property name=\"spaci"
  "ng\">6</property><child><object class=\"GtkLabel\" id=\"label10\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"xalign\">0</property><property name=\"label"
  "\" translatable=\"yes\">_Edge resistance:</property><property name=\"us"
  "e_underline\">True</property><property name=\"selectable\">True</proper"
  "ty><property name=\"mnemonic_widget\">wrap_resistance_scale</property><"
  "/object><packing><property name=\"expand\">False</property><property na"
  "me=\"fill\">False</property><property name=\"position\">0</property></p"
  "acking></child><child><object class=\"GtkAlignment\" id=\"alignment4\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "False</property><property name=\"left_padding\">12</property><child><ob"
  "ject class=\"GtkBox\" id=\"hbox2\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"ori"
  "entation\">horizontal</property><property name=\"spacing\">12</property"
  "><child><object class=\"GtkLabel\" id=\"label13\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"label\" translatable=\"yes\" comments=\"Edge resistance\">&"
  "lt;i&gt;Small&lt;/i&gt;</property><property name=\"use_markup\">True</p"
  "roperty></object><packing><property name=\"expand\">False</property><pr"
  "operty name=\"fill\">False</property><property name=\"position\">0</pro"
  "perty></packing></child><child><object class=\"GtkScale\" id=\"wrap_res"
  "istance_scale\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">True</property><property name=\"orientation\">horizonta"
  "l</property><property name=\"adjustment\">adjustment4</property><proper"
  "ty name=\"restrict_to_fill_level\">False</property><property name=\"dra"
  "w_value\">False</property></object><packing><property name=\"expand\">T"
  "rue</property><property name=\"fill\">True</property><property name=\"p"
  "osition\">1</property></packing></child><child><object class=\"GtkLabel"
  "\" id=\"label14\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"label\" translatable"
  "=\"yes\" comments=\"Edge resistance\">&lt;i&gt;Wide&lt;/i&gt;</property"
  "><property name=\"use_markup\">True</property></object><packing><proper"
  "ty name=\"expand\">False</property><property name=\"fill\">False</prope"
  "rty><property name=\"position\">2</property></packing></child></object>"
  "</child></object><packing><property name=\"expand\">True</property><pro"
  "perty name=\"fill\">True</property><property name=\"position\">1</prope"
  "rty></packing></child></object><packing><property name=\"expand\">True<"
  "/property><property name=\"fill\">True</property><property name=\"posit"
  "ion\">1</property></packing></child></object></child></object></child><"
  "child type=\"label\"><object class=\"GtkLabel\" id=\"label6\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"label\" translatable=\"yes\">&lt;b&gt;Wrap work"
  "spaces when reaching the screen edge&lt;/b&gt;</property><property name"
  "=\"use_markup\">True</property></object></child></object><packing><prop"
  "erty name=\"expand\">False</property><property name=\"fill\">True</prop"
  "erty><property name=\"position\">1</property></packing></child><child><"
  "object class=\"GtkFrame\" id=\"frame3\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"label_xalign\">0</property><property name=\"shadow_type\">none</prope"
  "rty><child><object class=\"GtkAlignment\" id=\"alignment5\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"border_width\">6</property><property name=\"botto"
  "m_padding\">6</property><property name=\"left_padding\">12</property><c"
  "hild><object class=\"GtkBox\" id=\"hbox6\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"orientation\">horizontal</property><child><object class=\"GtkCheck"
  "Button\" id=\"box_move_check\"><property name=\"label\" translatable=\""
  "yes\">When _moving</property><property name=\"use_action_appearance\">F"
  "alse</property><property name=\"visible\">True</property><property name"
  "=\"can_focus\">True</property><property name=\"receives_default\">False"
  "</property><property name=\"use_underline\">True</property><property na"
  "me=\"draw_indicator\">True</property></object><packing><property name=\""
  "expand\">True</property><property name=\"fill\">True</property><propert"
  "y name=\"position\">0</property></packing></child><child><object class="
  "\"GtkCheckButton\" id=\"box_resize_check\"><property name=\"label\" tra"
  "nslatable=\"yes\">When _resizing</property><property name=\"use_action_"
  "appearance\">False</property><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">True</property><property name=\"receives_d"
  "efault\">False</property><property name=\"use_underline\">True</propert"
  "y><property name=\"draw_indicator\">True</property></object><packing><p"
  "roperty name=\"expand\">True</property><property name=\"fill\">True</pr"
  "operty><property name=\"position\">1</property></packing></child></obje"
  "ct></child></object></child><child type=\"label\"><object class=\"GtkLa"
  "bel\" id=\"label7\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property><property name=\"label\" translatab"
  "le=\"yes\">&lt;b&gt;Hide content of windows&lt;/b&gt;</property><proper"
  "ty name=\"use_markup\">True</property></object></child></object><packin"
  "g><property name=\"expand\">False</property><property name=\"fill\">Tru"
  "e</property><property name=\"position\">2</property></packing></child><"
  "child><object class=\"GtkFrame\" id=\"frame4\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">False</property><propert"
  "y name=\"label_xalign\">0</property><property name=\"shadow_type\">none"
  "</property><child><object class=\"GtkAlignment\" id=\"alignment13\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Fal"
  "se</property><property name=\"top_padding\">6</property><property name="
  "\"bottom_padding\">6</property><property name=\"left_padding\">18</prop"
  "erty><child><object class=\"GtkComboBox\" id=\"double_click_action_comb"
  "o\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"tooltip_text\" translatable=\"yes\""
  ">The action to perform when the title-bar is double-clicked</property><"
  "/object></child></object></child><child type=\"label\"><object class=\""
  "GtkLabel\" id=\"label8\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"label\" trans"
  "latable=\"yes\">&lt;b&gt;Double click _action&lt;/b&gt;</property><prop"
  "erty name=\"use_markup\">True</property><property name=\"use_underline\""
  ">True</property><property name=\"mnemonic_widget\">double_click_action_"
  "combo</property></object></child></object><packing><property name=\"exp"
  "and\">False</property><property name=\"fill\">True</property><property "
  "name=\"position\">3</property></packing></child></object><packing><prop"
  "erty name=\"position\">3</property></packing></child><child type=\"tab\""
  "><object class=\"GtkLabel\" id=\"label4\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"label\" translatable=\"yes\">Ad_vanced</property><property name=\"u"
  "se_underline\">True</property></object><packing><property name=\"positi"
  "on\">3</property><property name=\"tab_fill\">False</property></packing>"
  "</child></object><packing><property name=\"expand\">True</property><pro"
  "perty name=\"fill\">True</property><property name=\"position\">1</prope"
  "rty></packing></child></object></child><action-widgets><action-widget r"
  "esponse=\"-11\">help_button</action-widget><action-widget response=\"0\""
  ">close_button</action-widget></action-widgets></object><object class=\""
  "GtkSizeGroup\" id=\"sizegroup1\"><property name=\"mode\">vertical</prop"
  "erty><widgets><widget name=\"alignment17\"/><widget name=\"alignment18\""
  "/></widgets></object></interface>"
};

static const unsigned xfwm4_dialog_ui_length = 49799u;

